-- Expand micronutrient tracking on logged_meals and saved_meals
-- MFP tracks: saturated fat, trans fat, cholesterol, vitamin A/C, calcium, iron, potassium
-- We already have: fiber, sugar, sodium

ALTER TABLE logged_meals
  ADD COLUMN IF NOT EXISTS saturated_fat NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS trans_fat NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cholesterol NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS potassium NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vitamin_a NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vitamin_c NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS calcium NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS iron NUMERIC DEFAULT 0;

ALTER TABLE saved_meals
  ADD COLUMN IF NOT EXISTS saturated_fat NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS trans_fat NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cholesterol NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS potassium NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vitamin_a NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vitamin_c NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS calcium NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS iron NUMERIC DEFAULT 0;
